language: node_js
sudo: false
node_js:
  - "node"
install:
  - yarn
script:
  - yarn build
before-deploy:
  - yarn run predeploy
deploy:
  provider: surge
  project: ./build/
  skip_cleanup: true
branches:
  only:
    - master